### ISSUE TITLE
Aggregate other "publications"

### ISSUE THREAD

**Issue by bergsm** [MassMove/AttackVectors#1]
Not sure if you're aware already, but each publication has what looks like a list of other publications in the same region at the bottom of the site. Shouldn't be too difficult to whip up a web crawler to aggregate a list of all of their sites to add here. I can take a crack at it this weekend.
<img width="775" alt="Screen Shot 2020-02-21 at 11 03 17 AM" src="https://user-images.githubusercontent.com/24835644/75050603-45257180-549a-11ea-918d-abc963d6846f.png">

**Comment by mariotacke** [comment]
I did something similar with #3 to extract "other publications" and facebook page.
