### ISSUE TITLE
Search for exact text reveals similar domains

### ISSUE THREAD

**Issue by salt-die** [MassMove/AttackVectors#13]
A simple [duckduckgo search](https://duckduckgo.com/?q=%22Gas+prices+near+zip+code%22+%22for+the+week+of%22) for exact text shows similar domains that aren't listed yet.  Here's a few:
https://harfordnews.com/
https://montgomerymdnews.com/
https://howardconews.com/

**Comment by salt-die** [comment]
Following "Other Publications" gives a few more not listed:
https://baltimorecitywire.com/
https://annearundeltoday.com/
https://mdstatewire.com/
https://northbaltimorejournal.com/

**Comment by salt-die** [comment]
Interestingly, https://harfordnews.com/ also seems to link to https://www.montgomerynews.com/ which appears legit.  Possibly the link was meant to be to https://montgomerymdnews.com/

**Comment by Bermos** [comment]
Nice find. Tho I actually added these with ca0e07eabd1b209b18bebaab99fdc7ac6fedc388

**Comment by salt-die** [comment]
https://dupagepolicyjournal.com/  not listed in the pull request
This one is interesting, the politics section articles seem to be a different format from the other sites (at least from what I've seen so far).  The "Other Publications" linked from here should give a lot more new sites:
https://dekalbtimes.com/
https://kendallcountytimes.com/
https://lakecountygazette.com/
https://peoriastandard.com/
https://prairiestatewire.com/
https://quincyreporter.com/
https://rockislandtoday.com/
https://rockfordsun.com/
https://seillinoisnews.com/
https://sangamonsun.com/
https://southcentralreporter.com/
https://southcooknews.com/
https://swillinoisnews.com/
https://silnews.com/

https://lgis.co/ seems suspicious to me, but breaks the naming pattern and layout conventions.  Linked to from dupagepolicyjournal.

**Comment by Bermos** [comment]
I didn't check them all but the few I looked up are in the [sites.csv](https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/sites.csv) file.

**Comment by Bermos** [comment]
I didn't check them all but the few I looked up are in the [sites.csv](https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/sites.csv) file.

**Comment by salt-die** [comment]
Yes, they're all listed there, sorry.  Except https://lgis.co/ which links back to some of these sites.
https://lgis.co/our_publications
