### ISSUE TITLE
newsbreak.com

### ISSUE THREAD

**Issue by salt-die** [MassMove/AttackVectors#14]
This is not on the same network as the others.  I'm not entirely sure it isn't legit, but the facebook page and outbound links are extremely suspicious including sites on this list. It could just be an innocent aggregator though.  There's also newsbreak app.  If this isn't legit, I don't think it's related to Timpone's network of sites.

**Comment by mariotacke** [comment]
Looks to be another AI/NLP/ML news aggregator/content creator.

Owned by: Particle Media Inc., https://www.linkedin.com/company/particle-media-inc-/

**Comment by mentor20** [comment]
They look legit enough.
