### ISSUE TITLE
Code to add more domains

### ISSUE THREAD

**Issue by a-douwe** [MassMove/AttackVectors#15]
By including the code to append to the .csv files containing the domains, it would be much easier to create a pull request with more websites.

**Comment by mariotacke** [comment]
I'm actually loading up the CSV in Excel/Google Sheets and make edits there then save. We haven't really established a process of adding columns via code.

**Comment by mentor20** [comment]
We have started a collection of utils here:

https://github.com/MassMove/AttackVectors/tree/master/LocalJournals/utils
