### ISSUE TITLE
https://collegeparktoday.com/

### ISSUE THREAD

**Issue by linkhunter1** [MassMove/AttackVectors#27]
Again, Metric Media listed all over the site, and a whole new network of disinformation news sites with a completely different web design. 

https://collegeparktoday.com/

**Comment by linkhunter1** [comment]
Example of other websites in the network: https://lakebuenavistanews.com/

**Comment by laspamfightr** [comment]
Here's a few more:

IP: 34.227.210.63

apopkatimes.com
baldwinparktoday.com
collegeparktoday.com
doctorphillipstoday.com
goldenrodnews.com
gothatoday.com
hunterscreeknews.com
lakebuenavistanews.com
lakebutlernews.com
lakehartnews.com
lakenonatoday.com
maitlandtoday.com
ocoeetoday.com
wadeviewparknews.com
windermeretoday.com

**Comment by laspamfightr** [comment]
I'm currently working on a pull request to add these sites. Just a heads up in case anyone else is looking through the issues.

**Comment by mentor20** [comment]
Great find @linkhunter1!
@laspamfightr you still got this? Otherwise I can add them...
