### ISSUE TITLE
https://fdahealthnews.com/

### ISSUE THREAD

**Issue by linkhunter1** [MassMove/AttackVectors#29]
It gets juicer! 

https://fdahealthnews.com/
https://www.facebook.com/FDAHealthNews/

Owned by Locality Labs: https://fdahealthnews.com/privacy

**Comment by laspamfightr** [comment]
IP: 54.152.78.38

advantageinformatics.com
americanwatchdogs.org
bartforillinois.com (404)
contentservices.co
electcolonelcraigwilcox.com (404)
fdahealthnews.com 
fdareporter.com 
franklinarcher.com
libertyprinciples.com 
therecordinc.com
tobacconewswire.com
toniaforillinois.com (404)
urbanreform.org
votejillian.com (404)
westlooptoday.com

**Comment by mentor20** [comment]
Very juicy! franklinarcher.com/our_publications#mbd lists 100 new domains.
