### ISSUE TITLE
https://hansondirectory.com/

### ISSUE THREAD

**Issue by linkhunter1** [MassMove/AttackVectors#31]
https://hansondirectory.com/

Again, owned and operated by Locality Labs: https://hansondirectory.com/privacy

**Comment by laspamfightr** [comment]
Quite a lot on this one. 

IP: 34.194.209.70

adairmadisonnews.com
ankenyguide.com 
bentleyvilleguide.com
boonecountyguide.com 
boyervalleynews.com
buchanancountynews.com 
carrollcoguide.com
cedarfallsguide.com
clarkeunionnews.com
clintonreview.com
clivenews.com
columbusgroveguide.com
cornellransomguide.com 
crawfordcountytimes.com
cretereview.com 
dallascountyreview.com 
delawarecoguide.com
dewittreview.com 
dubuquecoguide.com 
egyptianreview.com
elkhornguide.com 
englishvalleyguide.com
fairfieldreview.com 
glendalesun.com 
glenelderguide.com
grayguide.com 
greenecountyguide.com 
grimesjournal.com 
grundyguide.com
guthriecountyguide.com
hansondirectory.com
humboldtreview.com 
idasacguide.com
indianolaguide.com
indiantownguide.com
jacksoncoguide.com
jaspercountyguide.com
johnstontimes.com
jonescountynews.com
lansingreporter.com
lynwoodtimes.com 
madisoncountyguide.com 
mahaskaguide.com
marioncountyguide.com
marshallguide.com
metroeasttoday.com 
millsfremontnews.com
miltonvaleguide.com
moapavalleyguide.com
montgomeryadamsnews.com
mtpleasantguide.com
northtexasreview.com
norwalktimes.com
orwellguide.com
ottumwaguide.com
oxfordmetoday.com
pagetaylornews.com
peculiarguide.com
peoriasun.com
pokalambroguide.com
poweshiekguide.com 
ringgolddecaturnews.com 
selahguide.com
shelbycountytimes.com
surprisejournal.com
tamaguide.com
uppertaconicguide.com 
urbandaletimes.com
wamegoguide.com 
warrencountynews.com
washingtoncoguide.com
waskomreview.com
waterlooreview.com
waukeetimes.com
westdesmoinesguide.com
westfieldreporter.com
wrightcountyguide.com

**Comment by mentor20** [comment]
Nice... it looks like hansondirectory.com may have payed Locality Labs, LLC to build the site... leaving it out for now.

Added these that were missing from sites.csv:

bentleyvilleguide.com
columbusgroveguide.com
cornellransomguide.com
glendalesun.com
hansondirectory.com
peoriasun.com
surprisejournal.com
uppertaconicguide.com
