### ISSUE TITLE
https://metrobusinessnetwork.com/

### ISSUE THREAD

**Issue by linkhunter1** [MassMove/AttackVectors#34]
https://metrobusinessnetwork.com/

I saw that some of the related sites in the network have been documented already, but I saw some were missed...

Here is a more complete list:

https://metrobusinessnetwork.com/
https://azbusinessdaily.com/
https://gabusinessdaily.com/
https://mdbusinessdaily.com/
https://njbusinessdaily.com/
https://orbusinessdaily.com/
https://utbusinessdaily.com/
https://cabusinessdaily.com/
https://ilbusinessdaily.com/
https://mabusinessdaily.com/
https://nybusinessdaily.com/
https://palmettobusinessdaily.com/
https://vabusinessdaily.com/
https://cobusinessdaily.com/
https://iabusinessdaily.com/
https://mibusinessdaily.com/
https://ncbusinessdaily.com/
https://sdbusinessdaily.com/
https://wabusinessdaily.com/
https://ctbusinessdaily.com/
https://mnbusinessdaily.com/
https://keystonebusinessnews.com/
https://ndbusinessdaily.com/
https://tnbusinessdaily.com/
https://flbusinessdaily.com/
https://labusinessdaily.com/
https://mobusinessdaily.com/
https://ohbusinessdaily.com/
https://txbusinessdaily.com/
https://wibusinessdaily.com/

**Comment by laspamfightr** [comment]
Most of those are already on the sites list. Here's two that are missing
IP: 34.234.42.207

mexicobusinessdaily.com
guatemalabusinessdaily.com
latinbusinessdaily.com
tinewsdaily.com
patientdaily.com
