### ISSUE TITLE
Add domains

### ISSUE THREAD

**Issue by jbc22** [MassMove/AttackVectors#46]
Found these via AddThisPubID tracking ID ra-572bcb5be71832bd with highereducationtribune.com being the initial pivot point:

hostname | firstSeen | lastSeen
-- | -- | --
megadealernews.com | 2017-06-15 15:57:33 | 2019-12-01 00:43:23
highereducationtribune.com | 2019-08-06 18:09:12 | 2019-10-15 12:44:39
americansecuritynews.com | 2016-06-12 15:07:07 | 2019-09-16 15:49:55
hrdailywire.com | 2017-05-30 23:13:24 | 2018-09-11 19:16:29
maghrebnewswire.com | 2017-08-08 20:24:26 | 2017-10-19 15:01:57
dentalhealthwire.com | 2016-10-12 18:30:31 | 2017-09-24 20:54:58
tinewsdaily.com | 2016-06-02 16:55:22 | 2017-09-20 01:12:31
americanpharmacynews.com | 2016-05-18 13:04:55 | 2017-09-15 21:27:05
gulfnewsjournal.com | 2016-05-10 02:17:32 | 2017-09-10 13:23:48
patientdaily.com | 2016-05-27 23:15:13 | 2017-08-26 06:13:05
balkanbusinesswire.com | 2017-01-24 22:42:51 | 2017-08-14 18:52:28
latinbusinessdaily.com | 2017-06-12 13:56:29 | 2017-06-12 13:56:29
cropprotectionnews.com | 2016-05-22 22:01:23 | 2017-06-06 07:20:09
vaccinenewsdaily.com | 2016-05-22 07:41:24 | 2017-05-24 22:01:50
farminsurancenews.com | 2017-03-30 04:00:01 | 2017-03-30 04:00:01
aminewswire.com | 2016-05-26 23:31:25 | 2017-03-12 11:04:32
flarecord.com | 2016-06-03 17:51:43 | 2017-03-09 12:34:36
westafricawire.com | 2016-05-24 01:14:45 | 2017-02-05 18:40:04
bioprepwatch.com | 2016-11-09 05:38:46 | 2016-11-09 05:38:46

**Comment by mentor20** [comment]
Great find! Some of them ended up in [zombies.csv](https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/zombies.csv):
dentalhealthwire.com
vaccinenewsdaily.com
aminewswire.com
bioprepwatch.com

This is too weird: https://web.archive.org/web/20180819171433/https://aminewswire.com/ => privacy policy then follow the URL and finally the LinkedIn link.
