### ISSUE TITLE
Geotag domains

### ISSUE THREAD

**Issue by mariotacke** [MassMove/AttackVectors#5]
It would be great to find approximate coordinates for the cities and regions having dedicated domains. This would show us concentrations of misinformation. This information would be most useful when it is added to the `sites.csv` file for easy processing.

From what I can gather, the domains roughly follow this pattern:
`<city|region>[reporter|times|leader|today|news|wire|standard|sun|review]`

Stripping away the suffix and running the city/region through Google maps should give us a general idea in most cases.

**Comment by Bermos** [comment]
I tried to go there yesterday using open street maps api (overpass). 2 problems I found:

- The api is horrible (at least from what I'm used to working with modern web api design) and I still haven't figured out how to to only get cities/counties/regions/hamlet(?) and not just about everything (there are sooo many 'Miami' ice cream shops you wouldn't believe it. Plus even if I only get the selection there are still multiple possible locations for a lot of the results, so there would be the need for manual review.
- There is a lot more information for every request that might be interesting such as population which makes me think that a csv might no be the best way to store this information we gather.

**Comment by mariotacke** [comment]
Awesome. While going through the dumps, I've noticed lots of generated articles that mention ZIP code, ex: `/stories/525795952-best-station-to-purchase-regular-gas-near-zip-code-27253`. We could grep them which might give us better locations per publication.

**Comment by mariotacke** [comment]
Doing this for `ashevillereporter.com` stories:
```
cat ashevillereporter.com-stories | grep -Po 'zip-code-\d+' | awk -F"-" '{print $3}' | sort | uniq
```

results in these ZIP-codes:

```
22803
28701
28704
28707
28709
28710
28711
28715
28716
28721
28728
28730
28732
28735
28737
28745
28748
28751
28753
28754
28758
28759
28776
28778
28785
28786
28787
28801
28803
28804
28805
28806
28813
28814
28815
28816
```

**Comment by Bermos** [comment]
Nice. As far as I can tell there is no good system for matching the first 3 digits to a area/city since the 28800 is not defined. So we problably would have to search for "Ashville near 28815" or something. But it's late and my brain is not up to that task. Will think of something tomorrow.

**Comment by lmoroney** [comment]
I made a [PR](https://github.com/MassMove/AttackVectors/pull/18) to add a CSV with geocoded versions of the stripped domains.

Working on improving it to write them to your CSV.

Also working on a map with these plotted as pins

**Comment by lmoroney** [comment]
Plotted pins on the map at this [PR](https://github.com/MassMove/AttackVectors/pull/20)

**Comment by mentor20** [comment]
Added a shitty biohazard icon in #35 so the map plots on any system and added it to the readme and pinned it to the wall in the war room.

**Comment by lmoroney** [comment]
Nice! Can I get a photo of the map in the war room? Would love to see it :)

**Comment by mentor20** [comment]
I meant the virtual one: https://github.com/MassMove/WarRoom. 🎖

**Comment by codehtmai** [comment]
It might be worth adding a "location verified" column to the CSV. I've started checking some of the mapped locations, and many are wrong. It could be helpful to know which ones have already been checked and verified.

**Comment by mentor20** [comment]
Thanks for starting to check, @codehtmai - a locationVerified has been added: https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/sites-geocoded.csv
