### ISSUE TITLE
Update based on fb:pages

### ISSUE THREAD

**Issue by amneacsu** [MassMove/AttackVectors#53]
Hey, folks! Love your work!

I've been looking at `<meta name="fb:pages" content="(\d+)" />` tags, and although I've confirmed most of the Facebook pages reported in sites.csv, some are apparently pointing to different pages, while some are new (not tracked in sites.csv). What I did was take the FB page ID from the scraped sites and open facebook.com/:id. Following is a list of FB page IDs, urls, and domains listed in sites.csv that don't match what's currently in the repo, or are not filled in.

```
440850842779072 - https://www.facebook.com/dupagepolicyjournal/
annearundeltoday.com - new
baltimorecitywire.com - new
northbaltimorejournal.com - new

299588323424419 - https://www.facebook.com/legalnewsline/
cookcountyrecord.com - stored here as facebook/cookcountyrecord
socalrecord.com - new

573209409408570 - https://www.facebook.com/CookCountyRecord/
setexasrecord.com - stored here as facebook/SETexasRecord
stlrecord.com - stored here as facebook/stlrecord
```

As an aside

What's interesting to me is the Legal Newsline connection. I initially started scraping for "GET THE APP" (before noticing there's already a column in the CSV for that), and was looking at ["The Record, Inc."](https://apps.apple.com/us/developer/the-record-inc/id665945891
) developer. Their apps use the same orange shower-looking thing that's in the Legal Newsline logo. ~I did a reverse image search for that and found another developer that has since changed logos: [Right Mobile Pty Ltd](https://apps.apple.com/us/developer/right-mobile-pty-ltd/id998914240), [from this search](https://www.google.com/search?hl=en-RO&tbs=sbi:AMhZZitFeZ6NyYd0C7Or7LRoGkk95wkGllCiwjmFVMSlUu4tlTE0qc7MTNRjohEWGyPbBT6WVq-6ojmlF-Y9pLywnarAYWPfeakjEQirO-afMNPgCGz4HYqvCv7Rjm00DCEHh182RA_1W-pAaS1KYlfsvO6j_1anNoB5fEMGIbMK6w8Jl-29c95aR3QbbKHu36wfYDvSKYWDNvtG-q1N71wBhtsxcRaxe7DgpN4_1ipfkOFJfwckAM-a_1ny8iQplSD6Qb5Y-oid1TN3Du1EsGb5Uay-mYix8gYpaeAfg5s0if32ovT7kiLxBescmxPA1yO1BxcpbPacUTfbpwv9ca28RXDOBz_1LBzwvkg&ei=nF9xXuLSA-HmrgSj17zwCA&start=10&sa=N&ved=2ahUKEwjikIyJ16LoAhVhs4sKHaMrD44Q8NMDegQICxA1&biw=1440&bih=721). They have a bunch of republican/conservative apps, but haven't looked into it beyond that.~ I guess it makes sense if they're looking to change laws.

Not sure how much help this is, but I had fun.

Keep up the good work!

Edit: I may have misinterpreted the reverse image search results. I think it's catching the related apps section.

**Comment by mentor20** [comment]
Thanks, love your approach!

The new ones listed are in sites.csv, unless I missed something:

annearundeltoday.com - [#L745](https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/sites.csv#L745)
baltimorecitywire.com - [#L746](https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/sites.csv#L746)
northbaltimorejournal.com - [#L768](https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/sites.csv#L768)

Keep hunting.

Noroc, frate de arme!

**Comment by amneacsu** [comment]
> The new ones listed are in sites.csv, unless I missed something:

Their Facebook pages are "new", not the domains themselves. Sorry for the confusion.

**Comment by mentor20** [comment]
Ah, I think I see now. Can you run it for the new ones from [#L797](https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/sites.csv#L797)? They were added today.

**Comment by amneacsu** [comment]
I did now, but none of those have a `<meta name="fb:pages" />` tag. 🙁

**Comment by mentor20** [comment]
Thanks. Can you roll a script for us to extract the FB URLs for the new domains, like https://desmoinesguide.com/ => https://www.facebook.com/DesMoinesGuide/?

**Comment by amneacsu** [comment]
Sorry, not with my skillset. The only part I managed to automate was the scraping. I think anyone with any Python, C# or Bash experience could come up with something much better than I ever could. 😞

**Comment by mentor20** [comment]
All good, thanks for the inspiration... now you can add it to your skillset: https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/utils/FacebookUrlExtractor/Program.cs#L74-L85

Just found that the Legal Newsline connection goes deeper:
https://web.archive.org/web/20190806044945/https://legalnewsline.com/privacy
https://web.archive.org/web/20190426153606/cookcountyrecord.com/privacy
