### ISSUE TITLE
Blocklist for Pi-Hole?

### ISSUE THREAD

**Issue by jdurante** [MassMove/AttackVectors#66]
Hi,

Could you also make a blocklist that works with Pi Hole? https://pi-hole.net/.

I think it's almost exactly the same as the uBlock one, just without the pipes at the beginning of each domain.

Thanks!!

**Comment by karan** [comment]
I think if you use https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/fake-local-journals-list.txt and just strip the first line (`! Title: Fake-Local-Journals-List`), it should work.

**Comment by jdurante** [comment]
Cool thanks! I had to copy to my own repo and remove that line, so I'll have to manually update periodically, but that works for me. Thanks again.
