### ISSUE TITLE
Bad Locations/GeoLoc's.

### ISSUE THREAD

**Issue by wdjohnson** [MassMove/AttackVectors#67]
columbustandard.com is for Columbus, GA not Columbus, OH
bluestonenews.com is for somewhere in WV, not Columbus, OH

**Comment by IAmCoder** [comment]
Also added these: 

Dakota Times- 44.746945, -93.198948 (Dakota is a county, picked a fairly central city, Apple Valley)

East Twin Cities- * Maplewood 44.958345,-92.988034

NC Minnesota News-*Bemidji 47.505515,-94.884643

NW Minnesota News-*Grand Forks 47.928591,-97.038135

NW Twin Cities-*Maple Grove 45.068418,-93.455466

North Ramsey News-*North Oaks 45.090292,-93.082264

SE Minnesota News-*Rochester 44-009001,-92.510746

SE Twin Cities News-*Cottage Grove 44.828006, -92.940586

SW Minnesota Today-*Worthington 43.650662, -95.632320

WC Minnesota News- already mapped but I'd probably change it to something like Willmar 45.122341, -95.058689

West Twin Cities- already mapped but I'd probably change it to something like Minnetonka 44.921405, -93.483792

**Comment by IAmCoder** [comment]
And these:


URL | Wrong Location | Right Location
-- | -- | --
https://northpanhandletimes.com | SF, CA | 40.053113, -80.706908 (Northern Panhandle of WV)
https://westhillsboroughnews.com/ | Hillsborough, CA | 27.969968, -82.475962 (Hillsborough County, FL)
https://berkeleyleader.com/ | Berkeley, CA | 33.305644, -80.040642 (Berkeley County, SC)
https://northrichmondtoday.com/ | Richmond, CA | 37.558196, -77.434444 (Richmond, VA)
https://bluegrasstimes.com/ | Stockton, CA | 37.148198, -83.762946 (Clay County, Kentucky)
https://davistimes.com/ | Davis, CA | 41.012187, -112.022294 (Davis County, UT)
https://ncgeorgianews.com/ | Monterey, CA | 33.193150, -84.740641 (Articles were from all over GA, except Atlanta)
https://northfairfaxnews.com/ | West Hollywood, CA | 38.858443, -77.475914 (Northern Virginia, around Fairfax)
https://scvanews.com/ | Anaheim, CA | 37.399055, -79.103716 (Southern Virginia)
http://northcoastalnews.com/ | Oceanside, CA | 28.998429, -95.324834 (Northern gulf coast of Texas)
https://centralsdnews.com/ | Fresno, CA | 44.667091, -100.366677 (South Dakota)
