### ISSUE TITLE
Is there a single source of truth for the fake local journals?

### ISSUE THREAD

**Issue by jay3ss** [MassMove/AttackVectors#98]
I'm working on a Firefox extension that uses the [list of fake local journals](https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/fake-local-journals-list.txt), but I've also seen a few other lists/csv files around the repo and I just want to make sure that I'm pulling the list of confirmed fake local journals and that there isn't any other list in the repo that I should be using.

To make things a little clearer, I'm making a Firefox extension that injects a warning to sites that are known to be fake local journals.

**Comment by mentor20** [comment]
This is the master list: https://github.com/MassMove/AttackVectors/blob/master/LocalJournals/sites.csv

Let us know when your Firefox extension is ready and if we can link to it from the readme!

**Comment by jay3ss** [comment]
Fantastic, thanks a lot and I will let you know when it's ready.
